### POST CREATE AUTHORS

POST {{HOST}}/authors
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX1VTRVIifV0sImlhdCI6MTc0NTIzMTU3MywiZXhwIjoxNzQ1MjM1MTczfQ.IYS4Sc2mbwvidkSZr7Ij6bxC_Hee9IyhcqK5wPf6Nos

{
  "firstname": "John",
  "lastname": "Doe",
  "articleIds": []
}

